name: CI/CD Prueba1

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay cambios en main
  pull_request:
    branches:
      - main  # Se ejecuta en PRs hacia main

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Construir y subir imagen Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mi-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mi-app:${{ github.sha }}

  deploy:
    name: Deploy en Kubernetes
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Actualizar manifiestos y desplegar en Kubernetes
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ secrets.DOCKERHUB_USERNAME }}/mi-app:${{ github.sha }}|g" k8s/deployment.yaml
          kubectl apply -f k8s/

      - name: Verificar el estado del despliegue
        run: kubectl rollout status deployment/mi-app
